### ISSUE TITLE
Typo in Train/Test

### ISSUE THREAD

**Issue by shivangi-aneja** [aws-samples/d-SNE#4]
I think there is a typo in the following line of code
`https://github.com/aws-samples/d-SNE/blob/master/train_val/training_sda.py#L149`
It should be 
tes = cfg['SRC']['TEST']

**Comment by ShownX** [comment]
Hi, thank you for your comments. 
VisDA dataset is a dataset that adapting from synthetic image (source domain) to real image (target domain). It does not provide any test set from the synthetic image (source domain). For consistency with other datasets, I kept it like this since we only focus on the final performance on the target domain (real images).
